export default {
  CONNECTING: "CONNECTING",
  CONNECTED: "CONNECTED",
  DISCONNECTED: "DISCONNECTED",
  REGISTERED: "REGISTERED",
  UNREGISTERED: "UNREGISTERED",
  REGISTERFAILED: "REGISTERFAILED",
  REGISTER: "REGISTER_CALLER_ID",
  SIGN_OUT: "SIGN_OUT_CALLER_ID",
  SETCALLER: "SETCALLER",
  INCOMING_START: "INCOMING_START",
  INCOMING_END: "INCOMING_END",
  ACCEPT_CALL: "ACCEPT_CALL",
  DECLINE_CALL: "DECLINE_CALL",
  END_CALL: "END_CALL",
  TOGGLE_HOLD: "TOGGLE_HOLD",
  INCOMING_CHAT: "INCOMING_CHAT"
};
